### ISSUE TITLE
polyphone's classification

### ISSUE THREAD

**Issue by HeYingnan** [kakaobrain/g2pM#10]
hi, i find for anyone polyphone the netwok's output is a id, and then you can get pinyin from idx2class, i want to know how can you 
ensure the output id is one of the classifications? thank you.

**Comment by seanie12** [comment]
We map every pinyin to unique number (id) and save its inverse map (Id -> pinyin) into the dictionary, which is idx2class.

So we can convert the network's output into unique pinyin.
